apiVersion: v1
kind: Service
metadata:
  name: reflector
  labels:
    app.kubernetes.io/name: reflector
    app.kubernetes.io/part-of: packetparamedic
  annotations:
    # Uncomment the following for cloud provider LoadBalancer integration:
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reflector
  ports:
    - name: control
      port: 4000
      targetPort: 4000
      protocol: TCP
